### ISSUE TITLE
app crashes(freezes) with Dialogs

### ISSUE THREAD

**Issue by realtica** [fltk-rs/fltk-evented#1]
Hello, I have a modal dialog launched from event Button(btn):

 ```
while app.wait() {
        if btn.triggered() {
            info!("btn triggered");
            ConnectDialog::default();
            ..................
        }
       if hold_browser.triggered() {
            info!("hold_browser triggered");
            if hold_browser.value() != 0 {.......}
       }
```
If I use only the event Button(btn), all is ok.
But, if I interact with hold_browser event and attempt to launch the dialog again, the app crashes and stay freezes!.

This is my dialog, taked it from examples.

```
        win.end();
        win.make_modal(true);
        win.show();
        ok.set_callback({
            let mut win = win.clone();
            move |_| {
                win.hide();
            }
        });
        while win.shown() {
            app::wait();
        }
```
**If I remove the dialog, everything is ok.**

**Comment by MoAlyousef** [comment]
Hello
Thanks for the report. 
Can you provide more info about the OS as well as a minimally reproducible example?

Also does using btn.set_callback(|_| ConnectDialog::default()); outside the app.wait() loop work correctly?

**Comment by realtica** [comment]
Hello, 

```
Kernel:  5.10.0-11-amd64
Distro: Debian GNU/Linux 11 (bullseye)
CPU: AMD Ryzen 7 5800U with Radeon Graphics (16)
```
Working example: To reproduce the error open the dialog, close it select an item and try to open the dialog again.
Now, comment the MyDialog::default(); line and everithing will be ok.
```
[dependencies]
fltk = "^1.3"
fltk-evented = "0.1"
fltk-table = "0.1"

```


```
// use fltk::{app, button::Button, frame::Frame, group::Flex, prelude::*, window::Window};
use fltk::{prelude::*, *};
use fltk_evented::Listener;
use fltk_table::{SmartTable, TableOpts};

fn main() {
    let a = app::App::default();
    app::set_font_size(20);

    let mut wind = window::Window::default()
        .with_size(260, 400)
        .center_screen()
        .with_label("Counter");
    let flex = group::Flex::default()
        .with_size(220, 360)
        .center_of_parent()
        .column();
    let but_inc: Listener<_> = button::Button::default().with_label("Open dialog").into();
    let mut hold_browser: Listener<_> = browser::HoldBrowser::default().into();
    let mut table = SmartTable::default()
        .center_of_parent()
        .with_opts(TableOpts {
            rows: 30,
            cols: 15,
            editable: true,
            ..Default::default()
        });
    flex.end();
    wind.make_resizable(true);
    wind.end();
    wind.show();

    while a.wait() {
        if but_inc.triggered() {
            MyDialog::default();
            hold_browser.clear();
            hold_browser.add("item A");
            hold_browser.add("item b");
            hold_browser.add("item C");
        }
        if hold_browser.triggered() {
            table.set_opts(TableOpts {
                cell_align: enums::Align::Wrap,
                editable: false,
                rows: 30,
                cols: 15,
                ..Default::default()
            });
            for i in 0..30 {
                for j in 0..15 {
                    table.set_cell_value(i, j, &(i + j).to_string());
                }
            }
        }
        // frame.set_label(&val.to_string());
    }
    a.run().unwrap();
}

pub struct MyDialog {
    inp: input::Input,
}

impl MyDialog {
    pub fn default() -> Self {
        let mut win = window::Window::default()
            .with_size(400, 100)
            .with_label("My Dialog");
        let mut pack = group::Pack::default()
            .with_size(300, 30)
            .center_of_parent()
            .with_type(group::PackType::Horizontal);
        pack.set_spacing(20);
        frame::Frame::default()
            .with_size(80, 0)
            .with_label("Enter name:");
        let mut inp = input::Input::default().with_size(100, 0);
        let mut ok = button::Button::default().with_size(80, 0).with_label("Ok");
        pack.end();
        win.end();
        win.make_modal(true);
        win.show();
        ok.set_callback({
            let mut win = win.clone();
            move |_| {
                win.hide();
            }
        });
        while win.shown() {
            app::wait();
        }
        Self { inp }
    }
    pub fn value(&self) -> String {
        self.inp.value()
    }
}
```

**Comment by realtica** [comment]
Hello, 

```
Kernel:  5.10.0-11-amd64
Distro: Debian GNU/Linux 11 (bullseye)
CPU: AMD Ryzen 7 5800U with Radeon Graphics (16)
```
Working example: To reproduce the error just comment/uncomment the MyDialog::default(); line
```
[dependencies]
fltk = "^1.3"
fltk-evented = "0.1"
fltk-table = "0.1"

```


```
// use fltk::{app, button::Button, frame::Frame, group::Flex, prelude::*, window::Window};
use fltk::{prelude::*, *};
use fltk_evented::Listener;
use fltk_table::{SmartTable, TableOpts};

fn main() {
    let a = app::App::default();
    app::set_font_size(20);

    let mut wind = window::Window::default()
        .with_size(260, 400)
        .center_screen()
        .with_label("Counter");
    let flex = group::Flex::default()
        .with_size(220, 360)
        .center_of_parent()
        .column();
    let but_inc: Listener<_> = button::Button::default().with_label("Open dialog").into();
    let mut hold_browser: Listener<_> = browser::HoldBrowser::default().into();
    let mut table = SmartTable::default()
        .center_of_parent()
        .with_opts(TableOpts {
            rows: 30,
            cols: 15,
            editable: true,
            ..Default::default()
        });
    flex.end();
    wind.make_resizable(true);
    wind.end();
    wind.show();

    while a.wait() {
        if but_inc.triggered() {
            MyDialog::default();
            hold_browser.clear();
            hold_browser.add("item A");
            hold_browser.add("item b");
            hold_browser.add("item C");
        }
        if hold_browser.triggered() {
            table.set_opts(TableOpts {
                cell_align: enums::Align::Wrap,
                editable: false,
                rows: 30,
                cols: 15,
                ..Default::default()
            });
            for i in 0..30 {
                for j in 0..15 {
                    table.set_cell_value(i, j, &(i + j).to_string());
                }
            }
        }
        // frame.set_label(&val.to_string());
    }
    a.run().unwrap();
}

pub struct MyDialog {
    inp: input::Input,
}

impl MyDialog {
    pub fn default() -> Self {
        let mut win = window::Window::default()
            .with_size(400, 100)
            .with_label("My Dialog");
        let mut pack = group::Pack::default()
            .with_size(300, 30)
            .center_of_parent()
            .with_type(group::PackType::Horizontal);
        pack.set_spacing(20);
        frame::Frame::default()
            .with_size(80, 0)
            .with_label("Enter name:");
        let mut inp = input::Input::default().with_size(100, 0);
        let mut ok = button::Button::default().with_size(80, 0).with_label("Ok");
        pack.end();
        win.end();
        win.make_modal(true);
        win.show();
        ok.set_callback({
            let mut win = win.clone();
            move |_| {
                win.hide();
            }
        });
        while win.shown() {
            app::wait();
        }
        Self { inp }
    }
    pub fn value(&self) -> String {
        self.inp.value()
    }
}
```


> Hello,
> 
> ```
> Kernel:  5.10.0-11-amd64
> Distro: Debian GNU/Linux 11 (bullseye)
> CPU: AMD Ryzen 7 5800U with Radeon Graphics (16)
> ```
> 
> Working example: To reproduce the error just comment/uncomment the MyDialog::default(); line
> 
> ```
> [dependencies]
> fltk = "^1.3"
> fltk-evented = "0.1"
> fltk-table = "0.1"
> ```
> 
> ```
> // use fltk::{app, button::Button, frame::Frame, group::Flex, prelude::*, window::Window};
> use fltk::{prelude::*, *};
> use fltk_evented::Listener;
> use fltk_table::{SmartTable, TableOpts};
> 
> fn main() {
>     let a = app::App::default();
>     app::set_font_size(20);
> 
>     let mut wind = window::Window::default()
>         .with_size(260, 400)
>         .center_screen()
>         .with_label("Counter");
>     let flex = group::Flex::default()
>         .with_size(220, 360)
>         .center_of_parent()
>         .column();
>     let but_inc: Listener<_> = button::Button::default().with_label("Open dialog").into();
>     let mut hold_browser: Listener<_> = browser::HoldBrowser::default().into();
>     let mut table = SmartTable::default()
>         .center_of_parent()
>         .with_opts(TableOpts {
>             rows: 30,
>             cols: 15,
>             editable: true,
>             ..Default::default()
>         });
>     flex.end();
>     wind.make_resizable(true);
>     wind.end();
>     wind.show();
> 
>     while a.wait() {
>         if but_inc.triggered() {
>             MyDialog::default();
>             hold_browser.clear();
>             hold_browser.add("item A");
>             hold_browser.add("item b");
>             hold_browser.add("item C");
>         }
>         if hold_browser.triggered() {
>             table.set_opts(TableOpts {
>                 cell_align: enums::Align::Wrap,
>                 editable: false,
>                 rows: 30,
>                 cols: 15,
>                 ..Default::default()
>             });
>             for i in 0..30 {
>                 for j in 0..15 {
>                     table.set_cell_value(i, j, &(i + j).to_string());
>                 }
>             }
>         }
>         // frame.set_label(&val.to_string());
>     }
>     a.run().unwrap();
> }
> 
> pub struct MyDialog {
>     inp: input::Input,
> }
> 
> impl MyDialog {
>     pub fn default() -> Self {
>         let mut win = window::Window::default()
>             .with_size(400, 100)
>             .with_label("My Dialog");
>         let mut pack = group::Pack::default()
>             .with_size(300, 30)
>             .center_of_parent()
>             .with_type(group::PackType::Horizontal);
>         pack.set_spacing(20);
>         frame::Frame::default()
>             .with_size(80, 0)
>             .with_label("Enter name:");
>         let mut inp = input::Input::default().with_size(100, 0);
>         let mut ok = button::Button::default().with_size(80, 0).with_label("Ok");
>         pack.end();
>         win.end();
>         win.make_modal(true);
>         win.show();
>         ok.set_callback({
>             let mut win = win.clone();
>             move |_| {
>                 win.hide();
>             }
>         });
>         while win.shown() {
>             app::wait();
>         }
>         Self { inp }
>     }
>     pub fn value(&self) -> String {
>         self.inp.value()
>     }
> }
> ```

Also, I notice that the CPU usage is high than (btn.set_callback)

**Comment by MoAlyousef** [comment]
I think it's because the Dialog is calling app::wait(), and the but_inc.triggered code is also inside an app::wait. I would suggest placing the dialog code inside a set_callback() method, to avoid blocking the ui thread.

**Comment by realtica** [comment]
> I think it's because the Dialog is calling app::wait(), and the but_inc.triggered code is also inside an app::wait. I would suggest placing the dialog code inside a set_callback() method, to avoid blocking the ui thread.

I can't do that, because the items [hold_browser.add("item A");] depends of the dialog... 
Could you give me an example?

**Comment by realtica** [comment]
Is it possible that fltk-evented work with dialogs? If not please reopen this issue or add to documentation that this library doesn't support dialogs.

**Comment by MoAlyousef** [comment]
I don't the issue is in the evented crate, I think it's in the table crate. So I'll keep this closed, and the corresponding issue in the table crate open.
