### ISSUE TITLE
v0.5.1 compilation error only when `tokio` flag is enabled

### ISSUE THREAD

**Issue by CM-IV** [fltk-rs/fltk-evented#10]
**rustc** - 1.76.0
**rustup** - 1.27.0
**OS** - Debian 12 Bookworm

----

There seems to be an issue preventing the compilation of the `fltk-evented` crate with versions after `0.4.1`.  Both the `cargo check` and `cargo build` commands fail.

![image](https://github.com/fltk-rs/fltk-evented/assets/44551614/d74a3a68-c59a-432f-a44b-d9ea4906eec5)

The issue points toward a `include_str!` macro that cannot resolve its path correctly.

In an older version of the repo, the example docs just had the whole `main.rs` example file copy and pasted here instead of using a macro - would this possibly fix the issue?

**Comment by MoAlyousef** [comment]
Thank you for the report.
I've pushed a new version 0.5.2 which should have this issue fixed.
