### ISSUE TITLE
High usage of CPU

### ISSUE THREAD

**Issue by realtica** [fltk-rs/fltk-evented#2]
Hello,
```
Kernel:  5.10.0-11-amd64
Distro: Debian GNU/Linux 11 (bullseye)
CPU: AMD Ryzen 7 5800U with Radeon Graphics (16)
```
With a regular button the CPU usage is 0.5% with firefox open.
But with:
    `let mut btn: Listener<_> = button::Button::default().with_label("Connect").into();
`
The CPU usage increase and stay to 10%, what is happening?

**Comment by MoAlyousef** [comment]
Hello

It's because of the handler for events. I've removed them and published a version 0.2.0. Basically all on_event and evented methods unfortunately consumed high cpu.
