### ISSUE TITLE
add a `Listener::event() -> Event` method to instead the removed evented methods

### ISSUE THREAD

**Issue by viruscamp** [fltk-rs/fltk-evented#6]
I have added a `Listener::event() -> Event` method to instead the removed evented methods.  
It does not have the issue #2 .
```rust
    while app.wait() {
        match but_inc.event() {
            Event::Enter => { but_inc.set_color(Color::White); but_inc.redraw(); },
            Event::Leave => { but_inc.set_color(Color::BackGround); but_inc.redraw(); },
            _ => (),
        }
    }
```
There are 2 implements, which do you prefer?
  - a7d5b95fc203b52ea542c78529eccfe06854513a
    Simply just call `handle` and add `event()` even you don't need it.
  - 6d72daa1b95d0fdba4df5e82a512a78cbb8ccaa2
    User can choose one of the three, to avoid useless `handle` or `set_callback`.  
    The code uses some trait magic, looks not so simple. 
    `Listener` aka `ListenerWidget` has both methods, the public API is same as last one.  
    `TriggeredWidget` has `triggered() -> bool` only.  
    `EventWidget` has `event() -> Event` only.

**Comment by MoAlyousef** [comment]
I would prefer the first implementation. It's simpler to reason about :)
